# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'app'

# The type key specifies the language and version for your application.
type: 'golang:1.13'

build:
  flavor: composer

# The hooks that will be triggered when the package is deployed.
hooks:
  # Deploy hooks can access services but the file system is now read-only.
  build: |
    ls
#  deploy: |
#    mv mercure exec
#    chmod a+x exec/mercure
  post_deploy: |
    JWT_KEY='!ChangeMe!' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure


# The size of the persistent disk of the application (in MB).
disk: 2048

web:
  locations:
    '/':
      # The public directory of the app, relative to its root.
      root: 'public'
      # The front-controller script to send non-static requests to.
      passthru: '/index.html'

mounts:
  'exec':
    source: local
    source_path: exec