# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'app'

# The type key specifies the language and version for your application.
type: 'golang:1.13'

# The hooks that will be triggered when the package is deployed.
hooks:
  # Deploy hooks can access services but the file system is now read-only.
  build: |
    curl -o /mercure.tar.gz "https://github.com/dunglas/mercure/releases/download/v0.7.2/mercure_0.7.2_Linux_x86_64.tar.gz"
    tar xvzf mercure.tar.gz

web:
  commands:
    start: JWT_KEY='!ChangeMe!' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' ./mercure/mercure

  locations:
   /:
     # Route all requests to the Go app, unconditionally.
     # If you want some files served directly by the web server without hitting Go, see
     # https://docs.platform.sh/configuration/app/web.html
     allow: false
     passthru: true

mounts:
  'bin':
    source: local
    source_path: 'bin'

# The size of the persistent disk of the application (in MB).
disk: 1024