# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'app'

# The type key specifies the language and version for your application.
type: 'golang:1.13'

# The hooks that will be triggered when the package is deployed.
hooks:
  # Deploy hooks can access services but the file system is now read-only.
  build: |
    wget "https://github.com/dunglas/mercure/releases/download/v0.7.2/mercure_0.7.2_Linux_i386.tar.gz"
    ls
    tar xvzf mercure_0.7.2_Linux_i386.tar.gz
    ls
    rm mercure_0.7.2_Linux_i386.tar.gz
    chmod 777 mercure
  post_deploy: |
    ls

web:
  commands:
    start: |
      JWT_KEY='!ChangeMe!' ADDR=':3000' DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS='http://localhost:3000' DB_PATH=database/updates.db ./mercure

  locations:
   /:
     root: 'public'
     passthru: '/index.html'

mounts:
  'database':
    source: local
    source_path: database

# The size of the persistent disk of the application (in MB).
disk: 1024