# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'app'

# The type key specifies the language and version for your application.
type: 'golang:1.13'
size: S

# The hooks that will be triggered when the package is deployed.
hooks:
  # Deploy hooks can access services but the file system is now read-only.
  build: |
    wget "https://github.com/dunglas/mercure/releases/download/v0.7.2/mercure_0.7.2_Linux_x86_64.tar.gz"
    tar xvzf mercure_0.7.2_Linux_x86_64.tar.gz
    rm mercure_0.7.2_Linux_x86_64.tar.gz
    chmod 755 mercure
  post_deploy: |
    ls

web:
  commands:
    start: |
      JWT_KEY=$MERCURE_SECRET ADDR=:$PORT DEMO=1 ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=* PUBLISH_ALLOWED_ORIGINS=$MERCURE_PUBLISH_ALLOWED_ORIGINS DB_PATH=database/updates.db ./mercure

  locations:

    /:
      # Route all requests to the Go app, unconditionally.
      # If you want some files served directly by the web server without hitting Go, see
      # https://docs.platform.sh/configuration/app/web.html
      allow: false
      passthru: true

mounts:
  'database':
    source: local
    source_path: database

# The size of the persistent disk of the application (in MB).
disk: 1024